[tool.poetry]
name = "cookiecutters-data-science-test-project"
version = "0.1.0"
description = ""
authors = ["Timur Shaymardanov"]

[tool.poetry.dependencies]
python = "3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
